@get external x: Dom.domRect => float = "x"
@get external y: Dom.domRect => float = "y"
@get external width: Dom.domRect => float = "width"
@get external height: Dom.domRect => float = "height"
@get external top: Dom.domRect => float = "top"
@get external left: Dom.domRect => float = "left"
@get external bottom: Dom.domRect => float = "bottom"
@get external right: Dom.domRect => float = "right"
